<?php
/**
 * =============================================================
 * @file        $Id: controller.php 1.0.4 2013-05-11 00:00:00 Andrey Shlyapin $
 * @package	    oms 
 * @version     1.0.4
 * @class name  Controller
 * @description OMS
 * @copyright	  Copyright © 2013 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		  http://www.pokupaem-v-amerike.com/
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

jimport('joomla.application.component.controller');

class omsController extends JController
{
	/**
	 * Custom Constructor
	 */

	function __construct()
	{
		parent::__construct();
		
		$this->registerTask( 'add' , 'edit' );
		
	}
	
	/**
	 * display the edit form
	 * @return void
	 */
	function edit()
	{
		JRequest::setVar( 'layout', 'form'  );
		JRequest::setVar( 'hidemainmenu', 1);

		parent::display();
	}


	// Your custom code here


} // End class Controller
?>