<?php
/**
 * =============================================================
 * @file        $Id: oms.php 1.0.4 2013-05-11 00:00:00 Andrey Shlyapin $
 * @package	    oms 
 * @version     1.0.4
 * @description OMS
 * @copyright	  Copyright © 2013 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		  http://www.pokupaem-v-amerike.com/
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

require_once (JPATH_COMPONENT.DS.'helper.php');


$controller = JControllerLegacy::getInstance('oms');
$controller->execute(JRequest::getCmd('task', 'display'));
$controller->redirect();
?>