<?php
/**
 * =============================================================
 * @file        $Id: oms.php 1.0.4 2013-05-11 00:00:00 Andrey Shlyapin $
 * @package	    oms 
 * @version     1.0.4
 * @class name  Oms (Controller)
 * @description OMS
 * @copyright	  Copyright © 2013 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		  http://www.pokupaem-v-amerike.com/
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

jimport('joomla.application.component.controller');

/**
 * Controller class
 */
class omsControllerOms extends omsController
{



	/**
	 * constructor (registers additional tasks to methods)
	 * @return void
	 */
	function __construct()
	{
		parent::__construct();

    // Register Extra tasks
		// $this->registerTask( 'new' , 'save' );
	
	}  
	
} // end Controller class
?>