<?php
/**
 * =============================================================
 * @file        $Id: view.html.php 1.0.4 2013-05-11 00:00:00 Andrey Shlyapin $
 * @package	    oms 
 * @class name  Oms (View)
 * @version     1.0.4
 * @description OMS
 * @copyright	  Copyright © 2013 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		  http://www.pokupaem-v-amerike.com/
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

jimport( 'joomla.application.component.view' );
/**
 * View class
 */
class omsVieworders extends Jview
{



	function display($tpl = null){
		// global $mainframe;
	  
	  // YOUR CUSTOM CODE HERE
    
    // $this->assignRef('items', $items);
		OmsHelper::debug($this);
		parent::display($tpl);

	}


} // end View class

?>