<?php
/**
 * =============================================================
 * @file        $Id: form.php 1.0.4 2013-05-11 00:00:00 Andrey Shlyapin $
 * @package	    oms 
 * @version     1.0.4
 * @description OMS
 * @copyright	  Copyright © 2013 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Andrey Shlyapin
 * @author mail	andrey@skzd.ru
 * @website		  http://www.pokupaem-v-amerike.com/
 * =============================================================
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 */

// No direct access
defined( '_JEXEC' ) or die( 'Restricted access' );



	// YOUR CUSTOM CODE HERE

?>
<form action="index.php" method="post" name="adminForm">
<input type="hidden" name="option" value="com_oms" />
<input type="hidden" name="view" value="Oms" />
<input type="hidden" name="task" value="" />
<input type="hidden" name="boxchecked" value="0" />
</form>

